Vagrant.configure("2") do |config|
  # Configure private network
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "docker" do |docker|
    docker.image = "ubuntu:20.04"
    docker.has_ssh = true
  end
  

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/main.yml"
  end
end
